services:
  grafana:
    image: grafana/grafana:11.4.0
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus:v3.2.0
    command:
      - --config.file=/etc/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tempo:
    image: grafana/tempo:2.7.0
    command:
      - -config.file=/etc/tempo.yml
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
  loki:
    image: grafana/loki:3.3.1
    command:
      - -config.file=/etc/loki.yml
    volumes:
      - ./loki.yml:/etc/loki.yml
    ports:
      - "3100:3100"
