services:
  mongodb:
    image: mongo:8.0
    user: ${UID:-1000}:${GID:-1000}
    restart: unless-stopped
    env_file:
      - path: .env.default
        required: true
      # overrides the .env file
      - path: .env
        required: false
    volumes:
      - ./mongo-data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017
