name: Integration Feature Request
description: Request a new Feature in an existing Integration
title: "<Integration Name>: "
labels: ["enhancement", "integration"]
assignees:
  - SIMULATAN
body:
  - type: input
    id: contact
    attributes:
      label: Integration Name
      description: What Integration does this apply to?
      placeholder: ex. Moodle, Mapper
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Wanted Feature
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example Use Case
      description: Please state an example use case putting the feature into context.